In [1]:
import torch

In [ ]:
## y is scaler  
x = torch.arange(4.0)
x.requires_grad_(True)

y = 2 * torch.dot(x,x)
x.grad == 4 * x



tensor([ 0.,  4.,  8., 12.])


tensor([True, True, True, True])

In [8]:
## y is vector
## 清空梯度
x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)


y = x * x

y.sum().backward()

x.grad

tensor([2., 4., 6.])

In [11]:
## detach 保留数值，消除梯度
x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)


y = x * x

## u复制数值，但视为常数
u = y.detach()

z = u * x

z.sum().backward()

x.grad == u

x.grad.zero_()

y.sum().backward()

x.grad == 2 * x


tensor([True, True, True])

In [14]:
## 分段函数的梯度计算
def f(a):
    b = 2 * a
    while b.norm() < 1000:
        b = 2 * b
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size = (), requires_grad = True)
d = f(a)

d.backward()

## f(a) = k * a, hence k = d/a
a.grad == d/a


tensor(True)