In [1]:
import torch

In [ ]:
## 创建一个row vector
x = torch.arange(12)
x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
## 查看 shape 和 size
x.shape

print("Shape of x:", x.shape)

print("Size of x:", x.size())

Shape of x: torch.Size([12])
Size of x: torch.Size([12])


In [10]:
## reshape 改变tensor形状
X = x.reshape(3, 4)
X

## 也可以使用 -1 来自动推断某一维的大小
Y = x.reshape(-1, 4)
Y



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
## 创建 全0 tensor 
Z = torch.zeros((2,3,3))

Z


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [12]:
## 创建 全1 tensor
One = torch.ones((2,3,3))
One

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [16]:
## 从标准正态分布中随机采样创建tensor
Normal = torch.randn((1,3,3))
Normal

tensor([[[-0.1160,  1.0858, -0.3358],
         [ 0.1133,  1.0194, -0.5308],
         [-1.6949,  0.2303,  0.0785]]])