In [2]:
import torch
import pandas as pd
import numpy as np

In [3]:
## 一维tensor 就是数学中的 vector
x = torch.arange(4)

x[3]

tensor(3)

In [8]:
## matrix 
A = torch.arange(20).reshape(5,4)

print(A)

## A的转置
A.T

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
## 3维tensor
X = torch.arange(24).reshape(2,4,3)
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [18]:
## 矩阵运算
A = torch.arange(20).reshape(5,4)

B = A.clone()
## 加法
print(A + B)

## hadamard积
print(A * B)

## 降维（沿两个轴）
print(A.sum())

## 降维 （沿axis = 0）
A_sum_axis0 = A.sum(axis = 0)
print(A_sum_axis0)

## 降维 （沿axis = 1）
A_sum_axis1 = A.sum(axis = 1)
print(A_sum_axis1)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])
tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])
tensor(190)
tensor([40, 45, 50, 55])
tensor([ 6, 22, 38, 54, 70])


In [21]:
## 非降维求和
A = torch.arange(20).reshape(5,4)

sum_A = A.sum(axis = 1, keepdims = True)
print(sum_A)

## 利用broadcasting A/sum_A
print(A/sum_A)

## 累积元素和
print(A.cumsum(axis = 0))


tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])


In [24]:
## dot product
x = torch.tensor([0.0,1,2,3])
y = torch.ones(4, dtype = torch.float32)

print(torch.dot(x,y))

tensor(6.)


In [28]:
## marix-vector product
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
x = torch.ones(4, dtype = torch.float32)

mv_product = torch.mv(A,x)
print(mv_product)

tensor([ 6., 22., 38., 54., 70.])


In [31]:
## matrix-matrix multipltion

A = torch.arange(20, dtype = torch.float32).reshape(5,4)
x = torch.ones(4,3, dtype = torch.float32)

mm = torch.mm(A,x)
print(mm)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [9]:
## norm

## L2 norm
x = torch.tensor([3.0, -4.0])
L2_norm = torch.norm(x)
L2_norm

## L1 norm

L1_norm = torch.abs(x).sum()
L1_norm

## L_F norm
x = torch.ones(4,9)
LF_norm = torch.norm(x)
LF_norm

tensor(6.)